
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/departments
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: bikash
      password: 12
logging:
  level:
    org.springframework.security: TRACE
server:
  port: 8081
